<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>ICSharpCode.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="ICSharpCode.SharpZipLib" />
    <Reference Include="log4net">
      <HintPath>..\..\..\..\..\jenkins-workspaces\AccuraBuild\Clarion\bin\log4net.dll</HintPath>
    </Reference>
    <Reference Include="SoftVelocity.Ide.Core">
      <HintPath>..\..\..\..\..\jenkins-workspaces\AccuraBuild\Clarion\bin\SoftVelocity.Ide.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>