<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>ICSharpCode.SharpDevelop</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources.CodeGenerationOptionsPanel.xfrm" />
    <None Remove="Resources.CombineStartupPanel.xfrm" />
    <None Remove="Resources.CommonAboutDialog.xfrm" />
    <None Remove="Resources.EditStandardHeaderPanel.xfrm" />
    <None Remove="Resources.EditTemplateDialog.xfrm" />
    <None Remove="Resources.ExternalToolOptions.xfrm" />
    <None Remove="Resources.FontSelectionPanel.xfrm" />
    <None Remove="Resources.GeneralIDEOptionsPanel.xfrm" />
    <None Remove="Resources.NewFileWithNameDialog.xfrm" />
    <None Remove="Resources.InputBox.xfrm" />
    <None Remove="Resources.LoadSaveOptionPanel.xfrm" />
    <None Remove="Resources.NewFileDialog.xfrm" />
    <None Remove="Resources.NewProjectDialog.xfrm" />
    <None Remove="Resources.OutputWindowOptionsPanel.xfrm" />
    <None Remove="Resources.SelectStylePanel.xfrm" />
    <None Remove="Resources.TabbedOptionsDialog.xfrm" />
    <None Remove="Resources.TaskListOptions.xfrm" />
    <None Remove="Resources.TreeViewOptionsDialog.xfrm" />
    <None Remove="Resources.WordCountDialog.xfrm" />
    <None Remove="Resources.BehaviorTextEditorPanel.xfrm" />
    <None Remove="Resources.FindPanel.xfrm" />
    <None Remove="Resources.GotoDialog.xfrm" />
    <None Remove="Resources.ReplacePanel.xfrm" />
    <None Remove="Resources.GeneralTextEditorPanel.xfrm" />
    <None Remove="Resources.CodeTemplatePanel.xfrm" />
    <None Remove="Resources.MarkersTextEditorPanel.xfrm" />
    <None Remove="Resources.SortOptionsDialog.xfrm" />
    <None Remove="Resources.ProjectOptions.ApplicationSettings.xfrm" />
    <None Remove="Resources.ProjectOptions.Publish.xfrm" />
    <None Remove="Resources.ProjectOptions.Signing.xfrm" />
    <None Remove="Resources.ProjectOptions.BuildEvents.xfrm" />
    <None Remove="Resources.ProjectOptions.DebugOptions.xfrm" />
    <None Remove="Resources.CodeCompletionOptionPanel.xfrm" />
    <None Remove="Resources.ProjectOptions.CreateKey.xfrm" />
    <None Remove="Resources.FullscreenPanel.xfrm" />
    <None Remove="Resources.ProjectAndSolutionOptionsPanel.xfrm" />
    <None Remove="Resources.FontServiceOptionsPanel.xfrm" />
    <None Remove="Resources.IncrementalSearchCursor.cur" />
    <None Remove="Resources.ReverseIncrementalSearchCursor.cur" />
    <None Remove="Resources.ContractAll.png" />
    <None Remove="Resources.ExpandAll.png" />
    <None Remove="Resources.LocatorBeginWith.png" />
    <None Remove="Resources.LocatorButtonImage.png" />
    <None Remove="Resources.TreeClose.png" />
    <None Remove="Resources.TreeOpen.png" />
    <EmbeddedResource Include="Resources.CodeGenerationOptionsPanel.xfrm" LogicalName="Resources.CodeGenerationOptionsPanel.xfrm" />
    <EmbeddedResource Include="Resources.CombineStartupPanel.xfrm" LogicalName="Resources.CombineStartupPanel.xfrm" />
    <EmbeddedResource Include="Resources.CommonAboutDialog.xfrm" LogicalName="Resources.CommonAboutDialog.xfrm" />
    <EmbeddedResource Include="Resources.EditStandardHeaderPanel.xfrm" LogicalName="Resources.EditStandardHeaderPanel.xfrm" />
    <EmbeddedResource Include="Resources.EditTemplateDialog.xfrm" LogicalName="Resources.EditTemplateDialog.xfrm" />
    <EmbeddedResource Include="Resources.ExternalToolOptions.xfrm" LogicalName="Resources.ExternalToolOptions.xfrm" />
    <EmbeddedResource Include="Resources.FontSelectionPanel.xfrm" LogicalName="Resources.FontSelectionPanel.xfrm" />
    <EmbeddedResource Include="Resources.GeneralIDEOptionsPanel.xfrm" LogicalName="Resources.GeneralIDEOptionsPanel.xfrm" />
    <EmbeddedResource Include="Resources.NewFileWithNameDialog.xfrm" LogicalName="Resources.NewFileWithNameDialog.xfrm" />
    <EmbeddedResource Include="Resources.InputBox.xfrm" LogicalName="Resources.InputBox.xfrm" />
    <EmbeddedResource Include="Resources.LoadSaveOptionPanel.xfrm" LogicalName="Resources.LoadSaveOptionPanel.xfrm" />
    <EmbeddedResource Include="Resources.NewFileDialog.xfrm" LogicalName="Resources.NewFileDialog.xfrm" />
    <EmbeddedResource Include="Resources.NewProjectDialog.xfrm" LogicalName="Resources.NewProjectDialog.xfrm" />
    <EmbeddedResource Include="Resources.OutputWindowOptionsPanel.xfrm" LogicalName="Resources.OutputWindowOptionsPanel.xfrm" />
    <EmbeddedResource Include="Resources.SelectStylePanel.xfrm" LogicalName="Resources.SelectStylePanel.xfrm" />
    <EmbeddedResource Include="Resources.TabbedOptionsDialog.xfrm" LogicalName="Resources.TabbedOptionsDialog.xfrm" />
    <EmbeddedResource Include="Resources.TaskListOptions.xfrm" LogicalName="Resources.TaskListOptions.xfrm" />
    <EmbeddedResource Include="Resources.TreeViewOptionsDialog.xfrm" LogicalName="Resources.TreeViewOptionsDialog.xfrm" />
    <EmbeddedResource Include="Resources.WordCountDialog.xfrm" LogicalName="Resources.WordCountDialog.xfrm" />
    <EmbeddedResource Include="Resources.BehaviorTextEditorPanel.xfrm" LogicalName="Resources.BehaviorTextEditorPanel.xfrm" />
    <EmbeddedResource Include="Resources.FindPanel.xfrm" LogicalName="Resources.FindPanel.xfrm" />
    <EmbeddedResource Include="Resources.GotoDialog.xfrm" LogicalName="Resources.GotoDialog.xfrm" />
    <EmbeddedResource Include="Resources.ReplacePanel.xfrm" LogicalName="Resources.ReplacePanel.xfrm" />
    <EmbeddedResource Include="Resources.GeneralTextEditorPanel.xfrm" LogicalName="Resources.GeneralTextEditorPanel.xfrm" />
    <EmbeddedResource Include="Resources.CodeTemplatePanel.xfrm" LogicalName="Resources.CodeTemplatePanel.xfrm" />
    <EmbeddedResource Include="Resources.MarkersTextEditorPanel.xfrm" LogicalName="Resources.MarkersTextEditorPanel.xfrm" />
    <EmbeddedResource Include="Resources.SortOptionsDialog.xfrm" LogicalName="Resources.SortOptionsDialog.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.ApplicationSettings.xfrm" LogicalName="Resources.ProjectOptions.ApplicationSettings.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.Publish.xfrm" LogicalName="Resources.ProjectOptions.Publish.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.Signing.xfrm" LogicalName="Resources.ProjectOptions.Signing.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.BuildEvents.xfrm" LogicalName="Resources.ProjectOptions.BuildEvents.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.DebugOptions.xfrm" LogicalName="Resources.ProjectOptions.DebugOptions.xfrm" />
    <EmbeddedResource Include="Resources.CodeCompletionOptionPanel.xfrm" LogicalName="Resources.CodeCompletionOptionPanel.xfrm" />
    <EmbeddedResource Include="Resources.ProjectOptions.CreateKey.xfrm" LogicalName="Resources.ProjectOptions.CreateKey.xfrm" />
    <EmbeddedResource Include="Resources.FullscreenPanel.xfrm" LogicalName="Resources.FullscreenPanel.xfrm" />
    <EmbeddedResource Include="Resources.ProjectAndSolutionOptionsPanel.xfrm" LogicalName="Resources.ProjectAndSolutionOptionsPanel.xfrm" />
    <EmbeddedResource Include="Resources.FontServiceOptionsPanel.xfrm" LogicalName="Resources.FontServiceOptionsPanel.xfrm" />
    <EmbeddedResource Include="Resources.IncrementalSearchCursor.cur" LogicalName="Resources.IncrementalSearchCursor.cur" />
    <EmbeddedResource Include="Resources.ReverseIncrementalSearchCursor.cur" LogicalName="Resources.ReverseIncrementalSearchCursor.cur" />
    <EmbeddedResource Include="Resources.ContractAll.png" LogicalName="Resources.ContractAll.png" />
    <EmbeddedResource Include="Resources.ExpandAll.png" LogicalName="Resources.ExpandAll.png" />
    <EmbeddedResource Include="Resources.LocatorBeginWith.png" LogicalName="Resources.LocatorBeginWith.png" />
    <EmbeddedResource Include="Resources.LocatorButtonImage.png" LogicalName="Resources.LocatorButtonImage.png" />
    <EmbeddedResource Include="Resources.TreeClose.png" LogicalName="Resources.TreeClose.png" />
    <EmbeddedResource Include="Resources.TreeOpen.png" LogicalName="Resources.TreeOpen.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SmartPropertyGrid">
      <HintPath>C:\Clarion\Clarion11.1\bin\SmartPropertyGrid.dll</HintPath>
    </Reference>
    <Reference Include="Aga.Controls">
      <HintPath>C:\Clarion\Clarion11.1\bin\Aga.Controls.dll</HintPath>
    </Reference>
    <Reference Include="WeifenLuo.WinFormsUI.Docking">
      <HintPath>C:\Clarion\Clarion11.1\bin\WeifenLuo.WinFormsUI.Docking.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.Core">
      <HintPath>C:\Clarion\Clarion11.1\bin\ICSharpCode.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Build.Framework" />
    <Reference Include="ICSharpCode.TextEditor">
      <HintPath>C:\Clarion\Clarion11.1\bin\ICSharpCode.TextEditor.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.SharpDevelop.Dom">
      <HintPath>C:\Clarion\Clarion11.1\bin\ICSharpCode.SharpDevelop.Dom.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.SharpDevelop.Widgets">
      <HintPath>C:\Clarion\Clarion11.1\bin\ICSharpCode.SharpDevelop.Widgets.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.Build.Engine" />
    <Reference Include="ICSharpCode.NRefactory">
      <HintPath>C:\Clarion\Clarion11.1\bin\ICSharpCode.NRefactory.dll</HintPath>
    </Reference>
    <Reference Include="SeriousBit.Licensing">
      <HintPath>C:\Clarion\Clarion11.1\bin\SeriousBit.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="SoftVelocity.Ide.Core">
      <HintPath>C:\Clarion\Clarion11.1\bin\SoftVelocity.Ide.Core.dll</HintPath>
    </Reference>
    <Reference Include="ClarionDL">
      <HintPath>C:\Clarion\Clarion11.1\bin\ClarionDL.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>